
class Acidente(object):
    def __init__(self,     
        IdAcidente,
        Datahora,
        EntidadesFiscalizadoras,
        Velocidadelocal,
        Velocidadegeral,
        DiadaSemana,
        LatitudeGPS,
        LongitudeGPS,
        NumMortosa30dias,
        NumFeridosgravesa30dias,
        NumFeridosligeirosa30dias,
        CaracterísticasTecnicas1,
        CondAderência,
        Distrito,
        Concelho,
        Freguesia,
        PovProxima,
        Nomearruamento,
        TiposVias,
        CodVia,
        EstadoConservação,
        Km,
        FactoresAtmosféricos,
        RegCirculação1,
        IntersecçãoVias,
        Localizações,
        Luminosidade,
        MarcaVia,
        Natureza,
        ObrasArte,
        Obstáculos,
        Sentidos,
        Sinais,
        SinaisLuminosos,
        TipoPiso,
        Traçado1,
        Traçado2,
        Traçado3,
        Traçado4,
        ViaTrânsito):
            self.IdAcidente=IdAcidente
            self.Datahora=Datahora
            self.EntidadesFiscalizadoras=EntidadesFiscalizadoras
            self.Velocidadelocal=Velocidadelocal
            self.Velocidadegeral=Velocidadegeral
            self.DiadaSemana=DiadaSemana
            self.LatitudeGPS=LatitudeGPS
            self.LongitudeGPS=LongitudeGPS
            self.NumMortosa30dias=NumMortosa30dias
            self.NumFeridosgravesa30dias=NumFeridosgravesa30dias
            self.NumFeridosligeirosa30dias=NumFeridosligeirosa30dias
            self.CaracterísticasTecnicas1=CaracterísticasTecnicas1
            self.CondAderência=CondAderência
            self.Distrito=Distrito
            self.Concelho=Concelho
            self.Freguesia=Freguesia
            self.PovProxima=PovProxima
            self.Nomearruamento=Nomearruamento
            self.TiposVias=TiposVias
            self.CodVia=CodVia
            self.EstadoConservação=EstadoConservação
            self.Km=Km
            self.FactoresAtmosféricos=FactoresAtmosféricos
            self.RegCirculação1=RegCirculação1
            self.IntersecçãoVias=IntersecçãoVias
            self.Localizações=Localizações
            self.Luminosidade=Luminosidade
            self.MarcaVia=MarcaVia
            self.Natureza=Natureza
            self.ObrasArte=ObrasArte
            self.Obstáculos=Obstáculos
            self.Sentidos=Sentidos
            self.Sinais=Sinais
            self.SinaisLuminosos=SinaisLuminosos
            self.TipoPiso=TipoPiso
            self.Traçado1=Traçado1
            self.Traçado2=Traçado2
            self.Traçado3=Traçado3
            self.Traçado4=Traçado4
            self.ViaTrânsito=ViaTrânsito
        