
class CondutorVeiculo(object):    
    def __init__(self, 
        IdAcidente,
        Datahora,
        Sexo,
        Lesõesa30dias,
        LicençaCondução,
        TesteAlcool,
        AcçõesCondutores,
        InfCompaAcçõeseManobras,
        Nomeoutrosfactores,
        TempoConduçãoContinuada,
        AcessóriosCondutores,
        CategoriaVeículos,
        TipoVeiculo,
        TipoServiço,
        VeiculoEspecial,
        Anomatricula,
        InspecçãoPeriódica,
        CertificadoAdr,
        CargaLotação,
        Pneus,
        Seguros,
        Distrito,
        Concelho,
        Idade):
            self.IdAcidente=IdAcidente
            self.Datahora=Datahora
            self.Sexo=Sexo
            self.Lesõesa30dias=Lesõesa30dias
            self.LicençaCondução=LicençaCondução
            self.TesteAlcool=TesteAlcool
            self.AcçõesCondutores=AcçõesCondutores
            self.InfCompaAcçõeseManobras=InfCompaAcçõeseManobras
            self.Nomeoutrosfactores=Nomeoutrosfactores
            self.TempoConduçãoContinuada=TempoConduçãoContinuada
            self.AcessóriosCondutores=AcessóriosCondutores
            self.CategoriaVeículos=CategoriaVeículos
            self.TipoVeiculo=TipoVeiculo
            self.TipoServiço=TipoServiço
            self.VeiculoEspecial=VeiculoEspecial
            self.Anomatricula=Anomatricula
            self.InspecçãoPeriódica=InspecçãoPeriódica
            self.CertificadoAdr=CertificadoAdr
            self.CargaLotação=CargaLotação
            self.Pneus=Pneus
            self.Seguros=Seguros
            self.Distrito=Distrito
            self.Concelho=Concelho
            self.Idade=Idade
